reseltbitcamp/reselt

src/main/webapp/WEB-INF/views/shop/shopmain.jsp
=> shopmain.jsp : subcategory hide 추가 / svg 추가 / navi 수정

pom.xml, src/main/java/member/bean/MemberDTO.java, src/main/java/member/controller/MemberController.java, src/main/java/member/dao/MemberDAO.java, src/main/java/member/dao/MemberDAOMybatis.java, src/main/java/member/dao/memberMapper.xml, src/main/java/member/service/MemberService.java, src/main/java/member/service/MemberServiceImpl.java, src/main/java/spring/conf/SpringConfiguration.java, src/main/java/spring/db.properties, src/main/java/spring/mybatis-config.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/member/findEmail.jsp, src/main/webapp/WEB-INF/views/member/findPwd.jsp, src/main/webapp/WEB-INF/views/member/join.jsp, src/main/webapp/WEB-INF/views/member/kakao_login.jsp, src/main/webapp/WEB-INF/views/member/login.jsp
=> #33 DTO 오류 수정 및 로컬 DB 연결작업중

src/main/java/notice/bean/NoticeDTO.java, src/main/java/notice/controller/NoticeController.java, src/main/java/notice/dao/NoticeDAO.java, src/main/java/notice/dao/NoticeDAOMyBatis.java, src/main/java/notice/dao/noticeMapper.xml, src/main/java/notice/service/NoticeService.java, src/main/java/notice/service/NoticeServiceImpl.java, src/main/resources/spring/db.properties, src/main/resources/spring/mybatis-config.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/notice/noticeWriteForm.jsp
resolve #53 
공지사항 작성 페이지에서 글 작성하면 db에 저장
=> 공지사항 작성 DB연동

src/main/webapp/WEB-INF/views/myPage/buying.jsp, src/main/webapp/WEB-INF/views/myPage/myMain.jsp, src/main/webapp/WEB-INF/views/myPage/payment.jsp, src/main/webapp/WEB-INF/views/myPage/profile.jsp, src/main/webapp/WEB-INF/views/myPage/selling.jsp, src/main/webapp/WEB-INF/views/myPage/wish.jsp
=> My page 인코딩

src/main/java/shop/controller/ShopController.java, src/main/webapp/WEB-INF/views/shop/buyAgree.jsp, src/main/webapp/WEB-INF/views/shop/buyLastPage.jsp, src/main/webapp/WEB-INF/views/shop/buySize.jsp, src/main/webapp/WEB-INF/views/shop/buyStraight.jsp, src/main/webapp/WEB-INF/views/shop/sellAgree.jsp, src/main/webapp/WEB-INF/views/shop/sellSize.jsp, src/main/webapp/WEB-INF/views/shop/sellStraight.jsp, src/main/webapp/WEB-INF/views/shop/shopDetail.jsp, src/main/webapp/WEB-INF/views/shop/shopmain.jsp, src/main/webapp/WEB-INF/views/shopMenu/buyAgreeMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/buyBidMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/buySizeMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/buyStraightMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/sellAgreeMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/sellBidMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/sellSizeMenu.jsp, src/main/webapp/WEB-INF/views/shopMenu/sellStraightMenu.jsp
배송결제 페이지를 제외한 모든페이지 css 작업 완료했습니다.
=> #27 sell 배송/결제 페이지 제외한 모든 페이지 css 작업 후 스크립트 작성중

src/main/webapp/WEB-INF/views/style/styleMenu.jsp
1. Breadcrumb 가운데 정렬 완료
2. 우측 메뉴 살림.
하기 스크린샷 확인 부탁드립니다.
resolve #62
=> #62 styleWrite.jsp: breadcrumb 정렬, 메뉴 fix

src/main/webapp/WEB-INF/views/shop/sellStraight.jsp
pull요청 하셔서  pull 전에  commit하고 pr 날립니다~
=> #80-shop-sellScript "07-08 12:00 pull전 commit"

.project, src/main/java/notice/dao/NoticeDAOMyBatis.java, src/main/java/spring/conf/SpringConfiguration.java
Hot-fix due to the project migration
=> 87 merge comment conflict

src/main/webapp/WEB-INF/views/notice/noticeList.jsp
resolve #82 
jsp 추가 및 url 오류 수정
=> jsp 추가 및 url 오류 수정

src/main/java/notice/bean/NoticePaging.java, src/main/java/notice/service/NoticeService.java, src/main/java/notice/service/NoticeServiceImpl.java, src/main/webapp/WEB-INF/views/notice/noticeList.jsp
=> notice paging 완료

src/main/webapp/WEB-INF/views/shop/buyStraight.jsp, src/main/webapp/WEB-INF/views/shop/sellStraight.jsp
buyStraight, sellStraight 페이지 작업중 저장을 위해 pr 날립니다.
=> #84 buyStraight, sellStraight 작업중

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/assets/js/main/main.js
무한스크롤 로직 구현에 성공하였습니다.
차후 컨텐츠 로딩 관련해서 개발 진행하겠습니다.
=> 무한스크롤 로직 구현

src/main/webapp/WEB-INF/views/notice/etc/inspectionStandard.jsp, src/main/webapp/WEB-INF/views/shop/buyStraight.jsp, src/main/webapp/WEB-INF/views/shop/sellLastPage.jsp, src/main/webapp/WEB-INF/views/shop/sellStraight.jsp, src/main/webapp/WEB-INF/views/shopMenu/sellStraightMenu.jsp
=> 판매 마지막 페이지 구현중 팀장님 퇴근전 pr

src/main/webapp/WEB-INF/views/index.jsp, src/main/webapp/WEB-INF/views/main/main.jsp, src/main/webapp/assets/js/main/main.js
1. main.jsp에 무한스크롤 적용했습니다. 관련 코드는 /webapp/js/main/main.js에서 확인하실 수 있습니다.
2. 메인페이지에 무한스크롤 로직만 적용했습니다. 차후 어떤 컨텐츠를 불러올지 의논해서 적용하겠습니다.
resove #95
=> [Main] main.jsp: 무한스크롤 적용, showcase 반응형 디자인 적용

.gitignore, pom.xml, src/main/java/member/bean/MemberDTO.java, src/main/java/spring/db.properties
=> 120 migration to aws rds my sql

pom.xml, src/main/java/shop/controller/ShopController.java, src/main/java/spring/db.properties, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/INIStdPayBill.jsp, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/INIStdPayRelay.jsp, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/INIStdPayRequest.jsp, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/INIStdPayReturn.jsp, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/close.jsp, src/main/webapp/WEB-INF/views/shop/INIpayStdSample/popup.jsp, src/main/webapp/WEB-INF/views/shop/sellSuccess.jsp
=> 07-12 결제 api 연동 완료

src/main/java/style/controller/StyleController.java, src/main/java/style/dao/StyleDAO.java, src/main/java/style/dao/StyleDAOMyBatis.java, src/main/java/style/dao/styleMapper.xml, src/main/java/style/service/StyleService.java, src/main/java/style/service/StyleServiceImpl.java, src/main/webapp/WEB-INF/views/style/styleDetails.jsp, src/main/webapp/WEB-INF/views/style/styleList.jsp
=> [style] 상세페이지 DB 연결 및 삭제 기능 구현

src/main/java/member/bean/MemberDTO.java, src/main/java/member/controller/MemberController.java, src/main/java/member/dao/memberMapper.xml, src/main/java/member/service/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/member/join.jsp
=> 136 join emailconfirm

pom.xml, src/main/java/member/bean/MemberDTO.java, src/main/java/member/controller/MemberController.java, src/main/java/member/service/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/member/join.jsp, src/main/webapp/WEB-INF/views/member/logout.jsp
=> #160 비밀번호 DB 암호와 인코드 , 미팅 내용 반영 , memberDTO DB 칼럼 현신화 반영

src/main/java/myPage/bean/MyPageAddressDTO.java, src/main/java/myPage/controller/MyPageController.java, src/main/java/myPage/dao/MyPageAddressDAO.java, src/main/java/myPage/dao/MyPageAddressMybatis.java, src/main/java/myPage/dao/myPageAddressMapper.xml, src/main/java/myPage/dao/myPageBuyingMapper.xml, src/main/java/myPage/dao/myPageProfileMapper.xml, src/main/java/myPage/service/MyPageAddressService.java, src/main/java/myPage/service/MyPageAddressServiceImpl.java, src/main/java/myPage/service/MyPageProfileService.java, src/main/java/myPage/service/MyPageProfileServiceImpl.java, src/main/webapp/WEB-INF/views/myPage/address.jsp, src/main/webapp/WEB-INF/views/myPage/selling.jsp, src/main/webapp/WEB-INF/views/myPage/wish.jsp, src/main/webapp/WEB-INF/views/myPage/withdrawal.jsp, src/main/webapp/assets/css/myPage.css, src/main/webapp/assets/js/myPage/address.js, src/main/webapp/assets/js/myPage/buying.js, src/main/webapp/assets/js/myPage/withdrawal.js
=> 주소 페이지 작업 중

.vscode/settings.json, src/main/webapp/WEB-INF/views/shop/buyAgree.jsp, src/main/webapp/WEB-INF/views/shop/sellAgree.jsp, src/main/webapp/WEB-INF/views/shopMenu/tosModal.jsp
resolve #174 
대략적인 modal 기능 완료
디테일한 css는 추후 구현
=> [shop] 이용정책 modal 완료

src/main/java/member/dao/MemberDAO.java, src/main/java/member/dao/MemberDAOMybatis.java, src/main/java/member/dao/memberMapper.xml, src/main/java/member/service/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/member/join.jsp
=> #183 닉네임배틀태그, 비밀번호 복호화 코드추가

src/main/java/shop/bean/ProductInfoDTO.java, src/main/java/shop/controller/ShopController.java, src/main/java/shop/dao/ShopDAO.java, src/main/java/shop/dao/ShopDAOMybatis.java, src/main/java/shop/dao/shopMapper.xml, src/main/java/shop/service/ShopService.java, src/main/java/shop/service/ShopServiceImpl.java, src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/WEB-INF/views/shop/shopDetail.jsp, src/main/webapp/assets/js/shop/shopDetail.js, src/main/webapp/assets/js/shop/shopMain.js
for middle check sharing / saving
=> 187 shop dbing

src/main/java/search/controller/SearchController.java, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/views/main/menu.jsp, src/main/webapp/WEB-INF/views/search/searchMain.jsp
=> [search] front

src/main/java/myPage/controller/MyPageController.java, src/main/java/myPage/dao/MyPageProfileDAO.java, src/main/java/myPage/dao/MyPageProfileDAOMybatis.java, src/main/java/myPage/dao/myPageProfileMapper.xml, src/main/java/myPage/service/MyPageProfileService.java, src/main/java/myPage/service/MyPageProfileServiceImpl.java, src/main/webapp/WEB-INF/views/myPage/myMain.jsp, src/main/webapp/assets/js/myPage/myMain.js
=> #198 마이페이지 접근 권한 설정 및 회원탈퇴

src/main/webapp/WEB-INF/views/shop/shopDetail.jsp, src/main/webapp/assets/js/shop/shopDetail.js
shopDetail.js 이미지 갤러리를 중점으로 작업했습니다.
- 2개 이상의 이미지 로드
- 이미지 앞으로/뒤로 넘기기 버튼 behavior 추가
resolve #207
=> 207 shop detail fix

src/main/webapp/assets/js/shop/shopMain.js
=> 216 shop detail

src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/assets/js/shop/shopMain.js
merge 후 branch delete 부탁드려요 웅비시
=> 216-shop-infinite scroll

src/main/java/search/bean/SearchDTO.java, src/main/java/search/controller/SearchController.java, src/main/java/search/dao/SearchDAO.java, src/main/java/search/dao/SearchDAOMyBatis.java, src/main/java/search/dao/searchMapper.xml, src/main/java/search/service/SearchService.java, src/main/java/search/service/SearchServiceImpl.java, src/main/java/spring/conf/SpringConfiguration.java, src/main/java/spring/mybatis-config.xml, src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/search/searchMain.jsp, src/main/webapp/assets/js/search/searchList.js
resolve #205 
- db 연동
- 자동완성
구현 완료
=> [search] auto complete

src/main/java/shop/bean/BiddingDTO.java, src/main/java/shop/bean/OrdersDTO.java, src/main/java/shop/bean/ProductDTO.java, src/main/java/shop/controller/ShopController.java, src/main/java/shop/dao/ShopDAO.java, src/main/java/shop/dao/ShopDAOMybatis.java, src/main/java/shop/dao/shopMapper.xml, src/main/java/shop/service/ShopService.java, src/main/java/shop/service/ShopServiceImpl.java, src/main/java/spring/mybatis-config.xml, src/main/webapp/WEB-INF/views/shop/buySize.jsp, src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/WEB-INF/views/shopMenu/buySizeMenu.jsp, src/main/webapp/assets/js/shop/buyPage.js, src/main/webapp/assets/js/shop/shopDetail.js, src/main/webapp/assets/js/shop/shopMain.js
=> 07-25 Size페이지 back 작업중

src/main/webapp/assets/js/shop/shopDetail.js
간단하게 shopDetail 구매/판매 링크 수정했습니다.
resolve #229
=> #229 shopDetail: buySize, sellSize에 pid 파라미터 연동 완료

src/main/java/shop/bean/ProductDTO.java, src/main/java/shop/dao/shopMapper.xml, src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/assets/js/shop/shopMain.js
=> 227 shop filter

src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/assets/js/shop/shopMain.js
- 우상단 가격별 sorting 기능 구현 완료
- 좌측 사이드바에 필터링 기능 구현 완료
- Infinite scroll 기능 개선
resolves #237
=> 237 shop upperside filter

src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/WEB-INF/views/shop/main/shopmenu.jsp, src/main/webapp/assets/js/shop/shopMain.js, src/main/webapp/assets/js/shop/shopMain_jquery.js, src/main/webapp/assets/js/shop/shopMenu.js
- cdn 방식으로 isotope.js 사용하였습니다.  shopmain.jsp 와  shopmenu.jsp에 script tag로 추가해두었습니다.
- headerFilter 실행 순서는 shopmenu.jsp  상단 필터 버튼 -> shopmenu.js -> shopmain.jsp 입니다.
=> 248-shop-headerFilter console Err x

src/main/java/member/dao/memberMapper.xml
=> #258 회원가입 시 기본이미지 DB등록

src/main/java/style/bean/ReplyDTO.java, src/main/java/style/controller/StyleController.java, src/main/java/style/dao/styleMapper.xml, src/main/java/style/service/StyleService.java, src/main/java/style/service/StyleServiceImpl.java, src/main/webapp/WEB-INF/views/myPage/myMain.jsp, src/main/webapp/WEB-INF/views/style/styleDetails.jsp, src/main/webapp/WEB-INF/views/style/styleList.jsp, src/main/webapp/WEB-INF/views/style/styleUpdateForm.jsp, src/main/webapp/WEB-INF/views/style/styleWrite.jsp
resolved #257 
▶ 완료 작업
- 글, 댓글 작성시 등록 시간 기재
- 최신, 인기 필터 작업
▶ 남은 작업
- AWS 서버로 이미지 연동
- Style DB 작업
=> 257-style-백엔드 마무리

src/main/java/myPage/controller/MyPageController.java, src/main/webapp/WEB-INF/views/member/findEmail.jsp, src/main/webapp/WEB-INF/views/member/findPwd.jsp, src/main/webapp/WEB-INF/views/member/join.jsp, src/main/webapp/WEB-INF/views/member/login.jsp, src/main/webapp/WEB-INF/views/myPage/myMain.jsp, src/main/webapp/assets/js/myPage/profile.js
=> #265 프로필 추가 및 로그인 css 변경

src/main/java/shop/controller/ShopController.java, src/main/webapp/WEB-INF/views/shop/main/shopmain.jsp, src/main/webapp/assets/js/shop/shopMain.js, src/main/webapp/assets/js/shop/shopMain_jquery.js
(제출일 이후 조금씩 유지 보수 합니다.)
추가 되어야 할 항목
(1) svg logo 클릭 시 button function 실행 불가 (class id 중복 err) 
=> (function.js 는 작성 완료 상태입니다.)
(2) shopMenu.jsp 클릭 시 filter 기능 ( 실행 X )
=> 260-shop/index-last 제출일 기준 last commit
